### ISSUE TITLE
Android sample app crashes immediately on launch on tablet

### ISSUE THREAD

**Issue by bramley-turner-stride** [LivePersonInc/developers-community#155]
The Android sample app crashes immediately when launched on a tablet:
```
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                           at com.liveperson.sample.app.MainActivity.initSampleAppViews(MainActivity.java:151)
                                                                           at com.liveperson.sample.app.MainActivity.onCreate(MainActivity.java:78)
                                                                           at android.app.Activity.performCreate(Activity.java:6973)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
```

looks like a view is missing from the layout-sw600dp\activity_main.xml

**Comment by donmanguno** [comment]
Hi @bramley-turner-stride,

What version of the SDK are you using, on what kind of tablet running which Android version. Thanks.

**Comment by bramley-turner-stride** [comment]
3.0. I was building the sample from source (latest commit was https://github.com/LP-Messaging/Android-Messaging-SDK/commit/7b8824d31ca55e76d179233b0d3dd73b7fc96c88 )

**Comment by donmanguno** [comment]
Hi @bramley-turner-stride.  You're exactly right; the layout-sw600dp\activity_main.xml is missing a couple of elements.  I have submitted this to R&D and it will be corrected in a future release of the SDK.

For now you can replace the offending file with the attached, corrected one.
[activity_main.xml.zip](https://github.com/LivePersonInc/developers-community/files/1760055/activity_main.xml.zip)
