### ISSUE TITLE
Permanent problems with socket when using Messaging Agent SDK

### ISSUE THREAD

**Issue by zenkovnick-lp** [LivePersonInc/developers-community#191]
Hello, 

We are developing services to interact with LE using Messaging Agent SDK and facing all the time problems with the socket connection to LE. We've implemented socket ping using getClock method and often the result of the ping is socket errors with codes 1000, 1004 and 1006. Also LE often responds on ping and other requests with 401 and 502 status codes.

Example of 502 error:

```
   unexpected server response (502)
   at ClientRequest.response (/app/node_modules/node-agent-sdk/node_modules/ws/lib/WebSocket.js:719:15)
   at Object.onceWrapper (events.js:315:30)
   at emitOne (events.js:116:13)
   at ClientRequest.emit (events.js:211:7)
   at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
   at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
   at TLSSocket.socketOnData (_http_client.js:440:20)
   at emitOne (events.js:116:13)
   at TLSSocket.emit (events.js:211:7)
   at addChunk (_stream_readable.js:263:12)
   at readableAddChunk (_stream_readable.js:250:11)
   at TLSSocket.Readable.push (_stream_readable.js:208:10)
   at TLSWrap.onread (net.js:607:20)
```
Can you please advise what changes should we apply to avoid this errors?

Thanks!

**Comment by dvillacis94** [comment]
Hi @zenkovnick-lp,

Can you share the request/method your doing?

**Comment by shaymLP** [comment]
@zenkovnick-lp This post will be closed due to inactivity, if you have any further questions please do not hesitate to open a new one.
