### ISSUE TITLE
Expected to find a valid ContentProvider for this authority

### ISSUE THREAD

**Issue by sunilommi569** [LivePersonInc/developers-community#61]
App crashes when opening the activity with "showconversations" method when targeting  Android 'O'(26), please find below stack trace.
 LivePerson.showConversation(this, new LPAuthenticationParams(), new ConversationViewParams(true));

FATAL EXCEPTION: SocketHandler_Responses
                                                                              Process: com.tmobile.pr.mytmobile.dev, PID: 10829
                                                                              java.lang.SecurityException: Failed to find provider MessagesByBrandIDCursorLoader14791994 for user 0; expected to find a valid ContentProvider for this authority
                                                                                  at android.os.Parcel.readException(Parcel.java:1942)
                                                                                  at android.os.Parcel.readException(Parcel.java:1888)
                                                                                  at android.content.IContentService$Stub$Proxy.notifyChange(IContentService.java:801)
                                                                                  at android.content.ContentResolver.notifyChange(ContentResolver.java:2046)
                                                                                  at android.content.ContentResolver.notifyChange(ContentResolver.java:1997)
                                                                                  at android.content.ContentResolver.notifyChange(ContentResolver.java:1967)
                                                                                  at com.liveperson.messaging.model.AmsMessages.update(AmsMessages.java:127)
                                                                                  at com.liveperson.messaging.model.AmsMessages.updateHandledExConversation(AmsMessages.java:2029)
                                                                                  at com.liveperson.messaging.network.socket.ExConversationChangeNotificationResponseHandler.updateHandledExConversationCompleted(ExConversationChangeNotificationResponseHandler.java:308)
                                                                                  at com.liveperson.messaging.network.socket.ExConversationChangeNotificationResponseHandler.onHandleConversationCompleted(ExConversationChangeNotificationResponseHandler.java:301)
                                                                                  at com.liveperson.messaging.network.socket.ExConversationChangeNotificationResponseHandler.handle(ExConversationChangeNotificationResponseHandler.java:199)
                                                                                  at com.liveperson.messaging.network.socket.ExConversationChangeNotificationResponseHandler.handle(ExConversationChangeNotificationResponseHandler.java:43)
                                                                                  at com.liveperson.infra.network.socket.SocketHandler.handle(SocketHandler.java:214)
                                                                                  at com.liveperson.infra.network.socket.SocketHandler.access$1000(SocketHandler.java:31)
                                                                                  at com.liveperson.infra.network.socket.SocketHandler$WebSocketCallbacks$3.parseIncomingData(SocketHandler.java:425)
                                                                                  at com.liveperson.infra.network.socket.SocketHandler$WebSocketCallbacks$3.run(SocketHandler.java:371)
                                                                                  at android.os.Handler.handleCallback(Handler.java:789)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by donmanguno** [comment]
Hi Sunil, Which LP SDK version are you using? I was unable to reproduce this behavior on my application targeting Android 26 with LP SDK 2.8.

**Comment by sunilommi569** [comment]
Update on the issue:

Crashes in emulator , but works fine on device.
