### ISSUE TITLE
Insert our date and time info into the dataframe using our start_time_epoch - ERROR

### ISSUE THREAD

**Issue by ValAug** [LivePersonInc/developers-community#687]
What am I doing wrong - could you please advise?

```
for skill in skillIDs:
		df_.set_value(skill, "1589466060", myDate)
		df_.set_value(skill, "1589378867000", myTimeFrame)
		df_.set_value(skill, "158937886", myTimeZone)
```

```
We're working with these skills: FM_general
Traceback (most recent call last):
  File "le_03.py", line 91, in <module>
    df.set_value(skill, "1589466060", myDate)
  File "C:\Users\avaldivia1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'set_value'
```

**Comment by j9t** [comment]
Hi @ValAug—thanks for the extreme patience here…! We’re going through all open issues, working to ensure (much faster) responses; please let us know if this is still relevant.

**Comment by j9t** [comment]
(Closing in acknowledgement of long communication delay; we’re there to pick this up again.)
