### ISSUE TITLE
While clicking LP Notification - App crashed .

### ISSUE THREAD

**Issue by SanilDas** [LivePersonInc/developers-community#79]
Hi Team ,
I am working on Live Person Chat integration using cordova plugin in android app .  
For me  chat is working fine and can able to get notification from LP agent while chat is going to  background. 
While clicking on  Notification in the device , it  should be redirect to LP chat screen .But Application is getting crashed while reconnecting chat . I am getting  "Null pointer exception " in the LP sdk  because of jwt token . 
I am sending a jwt token from java script side . Here I have attached my logs .Please check it . 

Please help me if someone is facing same issue . This issue happening after migrated LP SDK from 2.5 to 2.8. 

            java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.liveperson.infra.LPAuthenticationParams.getHostAppJWT()' on a null object reference
                                                       at com.liveperson.messaging.model.AmsAccount.isHostAppJWTExpired(AmsAccount.java:148)
                                                       at com.liveperson.messaging.controller.AccountsController.isTokenExpired(AccountsController.java:82)
                                                       at com.liveperson.messaging.controller.connection.ConnectionStateMachine$ConnectingState.actionOnEntry(ConnectionStateMachine.java:260)
                                                       at com.liveperson.infra.statemachine.BaseStateMachine.changeState(BaseStateMachine.java:70)
                                                       at com.liveperson.messaging.controller.connection.ConnectionStateMachine$DisconnectedState.visit(ConnectionStateMachine.java:878)
                                                       at com.liveperson.messaging.controller.connection.connectionevents.ForegroundEvent.accept(ForegroundEvent.java:18)
                                                       at com.liveperson.infra.statemachine.StateMachineExecutor$RunnableWrapper.run(StateMachineExecutor.java:26)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by SanilDas** [comment]
Hi ,
I am using below method for start conversion and it is working fine in start conversion .
showConversation(Activity activity, LPAuthenticationParams lpAuthenticationParams, ConversationViewParams params‎)

But I am getting problem while clicking on  LP notification from LP agent when app is background ,application getting crashed . Because I have handled message in FCMMessage.java class , below method for default notification .

LivePerson.handlePushMessage(this, remoteMessage.getData(), account, true);

If i make flag false , i wont get default notification  . Please let me know if you face same issue .

**Comment by dvillacis94** [comment]
Hi, 

Usually you'll need to handle the push, that means parsing the LP Object, then you display the push.

`
PushMessage message = LivePerson.handlePushMessage(this, remoteMessage.getData(), account), false);
      //Code snippet to add push UI notification
      if ( message != null ) {
        // Show Notification
        NotificationUI.showNotification(this, message);
      }
`
can you share how are you handling the OnMessageReceived?

**Comment by orenkatz** [comment]
Hey @SanilDas , did @dvillacis94 suggestion resolved your issue?

**Comment by donmanguno** [comment]
I am closing this issue as there has been no response since David's recommendation.
