### ISSUE TITLE
[BUG] Local server startup is not possible

### ISSUE THREAD

**Issue by akirilyuk** [LivePersonInc/developers-community#974]
Hi,

after pulling the latest master changes, I cannot start the service anomore with npm run serve: 

I get this error:

/usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
  Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in /_layouts/default.html
jekyll 3.8.6 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
Traceback (most recent call last):
        58: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
        57: from /usr/local/opt/ruby/bin/bundle:23:in `load'
        56: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
        55: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        54: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
        53: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
        52: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        51: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
        50: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        49: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        48: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        47: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
        46: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
        45: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
        44: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
        43: from /usr/local/lib/ruby/gems/2.7.0/bin/jekyll:23:in `<top (required)>'
        42: from /usr/local/lib/ruby/gems/2.7.0/bin/jekyll:23:in `load'
        41: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/exe/jekyll:15:in `<top (required)>'
        40: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        39: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        38: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        37: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        36: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        35: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        34: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:93:in `start'
        33: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:93:in `each'
        32: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/serve.rb:93:in `block in start'
        31: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:36:in `process'
        30: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:65:in `build'
        29: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/command.rb:28:in `process_site'
        28: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:71:in `process'
        27: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:192:in `render'
        26: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:471:in `render_pages'
        25: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:471:in `each'
        24: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:472:in `block in render_pages'
        23: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:479:in `render_regenerated'
        22: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:62:in `run'
        21: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:88:in `render_document'
        20: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:158:in `place_in_layouts'
        19: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:195:in `render_layout'
        18: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/renderer.rb:126:in `render_liquid'
        17: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
        16: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
        15: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
        14: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
        13: from /usr/local/lib/ruby/gems/2.7.0/gems/jekyll-3.8.6/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
        12: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        11: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        10: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
         9: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
         8: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
         7: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         6: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
         5: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
         4: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
         3: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
         2: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
         1: from /usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:97:in `render'
/usr/local/lib/ruby/gems/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:97:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

Can you pleas check what broke this flow and fix it?

**Comment by ahuppert** [comment]
Same issue for me. I could fix it by renaming the following file that contains an apostrophe: pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ConfiguringtheSDK/configuring-the-message’s-edittext.md

**Comment by j9t** [comment]
Hi @akirilyuk, @ahuppert—thanks for the extreme patience here. Is this still an issue?

**Comment by j9t** [comment]
Thanks @ahuppert! We’ll keep an eye out and make adjustments where needed.
